name: artTheropyAIR
description: Art therapy recording app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+8

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  #flutter:
  #  sdk: flutter
  #flutter_localizations:
  #  sdk: flutter
  #algolia: ^1.1.2
  auto_size_text: 3.0.0
  cached_network_image: ^3.4.1
  #cloud_firestore: ^5.5.1
  #cloud_firestore_platform_interface: ^6.5.1
  #cloud_firestore_web: ^4.3.5
  #cloud_functions: ^5.2.0
  #cloud_functions_platform_interface: ^5.5.40
  #cloud_functions_web: ^4.10.5
  dropdown_button2: ^2.3.9
  equatable: ^2.0.7
  #file_picker: ^8.0.3
  #firebase_auth: ^5.3.4
  #firebase_auth_platform_interface: ^7.4.10
  #firebase_auth_web: ^5.13.5
  #firebase_core: ^3.8.1
  #firebase_core_platform_interface: ^5.3.1
  #firebase_core_web: ^2.18.2
  #firebase_messaging: ^15.1.6
  #firebase_messaging_platform_interface: ^4.5.49
  #firebase_messaging_web: ^3.9.5
  #firebase_storage: ^12.3.7
  #firebase_storage_platform_interface: ^5.1.34
  #firebase_storage_web: ^3.10.6
  floating_bottom_navigation_bar: 1.5.2
  flutter_animate: ^4.5.2
  flutter_cache_manager: ^3.3.1
  flutter_colorpicker: ^1.0.3
  flutter_plugin_android_lifecycle: ^2.0.23
  flutter_spinkit: ^5.2.1
  flutter_widget_from_html: 0.17.0
  fluttericon: ^2.0.0
  font_awesome_flutter: ^10.8.0
  from_css_color: 2.0.0
  fwfh_webview: ^0.15.3
  go_router: ^15.1.2
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  google_sign_in_android: ^6.1.34
  google_sign_in_ios: ^5.7.8
  google_sign_in_platform_interface: ^2.4.5
  google_sign_in_web: ^0.12.4+3
  html_editor_enhanced: ^2.7.1
  #html_editor_enhanced:
  #  git: https://github.com/eoinzy/html-editor-enhanced
  image_picker: ^1.1.2
  image_picker_android: ^0.8.12+18
  image_picker_for_web: ^3.0.6
  image_picker_ios: ^0.8.12+1
  image_picker_platform_interface: ^2.10.0
  intl: ^0.20.2
  json_path: ^0.7.4
  mime_type: ^1.0.1
  page_transition: ^2.1.0
  path_provider: ^2.1.5
  path_provider_android: ^2.2.15
  path_provider_foundation: ^2.4.1
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8
  pointer_interceptor: ^0.10.1
  provider: ^6.1.2
  rxdart: ^0.28.0
  shared_preferences: ^2.5.4
  #shared_preferences_android: ^2.3.4
  #shared_preferences_ios: 2.1.1
  #shared_preferences_platform_interface: ^2.4.1
  #shared_preferences_web: ^2.4.2
  sign_in_with_apple: ^7.0.1
  sign_in_with_apple_platform_interface: ^2.0.0
  sign_in_with_apple_web: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  sqflite: ^2.4.1
  stream_transform: ^2.1.1
  timeago: ^3.7.1
  universal_io: ^2.2.2
  url_launcher: ^6.3.1
  url_launcher_android: ^6.3.14
  url_launcher_ios: ^6.3.2
  url_launcher_platform_interface: ^2.3.2
  #flutter_intro: ^2.3.1
  #video_player: ^2.9.2
  #video_player_android: ^2.7.16
  #video_player_avfoundation: ^2.6.5
  #video_player_platform_interface: ^6.2.3
  #video_player_web: ^2.3.3
  cupertino_icons: ^1.0.0
  infinity_view: ^1.0.0
  fluttertoast: ^8.2.10
  motion_toast: ^2.11.0
  number_inc_dec: ^0.8.0
  scroll_to_hide: ^2.1.0
  universal_html: ^2.2.4
  flutter_super_html_viewer:
  #appwrite: 17.0.1
  appwrite: 21.0.0
  window_location_href: ^1.0.1+2
  date_format: ^2.0.9
  latlng: ^2.0.0
  flutter_localization: ^0.3.2
  #fastor_app_ui_widget: ^1.3.61
  http: ^1.1.2
  #quill_html_editor: ^2.2.8
  #below added for Html Editor Enhanced
  flutter_keyboard_visibility: ^6.0.0
  visibility_detector: ^0.4.0+2
  numberpicker: ^2.1.2
  fwfh_svg: ^0.16.0
  flutter_svg: ^2.1.0
  flutter_inappwebview: ^6.1.51
  arrow_pad: ^0.2.0
  clipboard: ^0.1.3
  platform_file: ^0.1.0
  chiclet: ^1.2.0
  dotted_border: ^3.1.0
  web: ^1.1.1
  dio: ^5.9.0
  cron: ^0.6.2
  video_player: ^2.10.1

  flutter_staggered_grid_view: ^0.7.0
  animated_text_kit: ^4.3.0




dependency_overrides:
  flutter_web_auth_2: 4.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  build_runner: ^2.4.10
  injectable_generator: 2.7.0
  json_serializable: ^6.9.5


    #flutter_test:
  #sdk: flutter


flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/images/app_launcher_icon.png'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
#    - assets/html/


  fonts:
    - family: 'CustomIcons'
      fonts:
        - asset: assets/fonts/custom_icons.ttf
          weight: 600


    - family: CustomIcons
      fonts:
        - asset: assets/fonts/custom_icons.ttf
    - family: Icomoon
      fonts:
        - asset: assets/fonts/icomoon.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf
    - family: 'material-icons'
      fonts:
        - asset: assets/fonts/MaterialIcons-Regular.ttf
    - family: 'MaterialIcons'
      fonts:
        - asset: assets/fonts/MaterialIcons-Regular.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
